content-type: application/x-www-form-urlencoded;charset=utf-8

token-request:
  uri: https://kauth.kakao.com/oauth/token
  body:
    grant-type: authorization_code
    client-id: a33a6ac40ea15278b115b07b8250e8ea
    request-uri: http://localhost:8080/auth/kakao/callback

profile-request:
  uri: https://kapi.kakao.com/v2/user/me

cos:
  cosKey: cos1234